AWSTemplateFormatVersion: 2010-09-09
Parameters:

  clusterName:
    Type: String

  taskName:
    Type: String
    Default: locust-load-test

  ecrRepo:
    Type: String
    Default: ml-serving/locust-loadtest

  perfTestBucket:
    Type: String

  loadTestImage:
    Type: String
    Default: latest

  subnet1Cidr:
    Type: String

  subnet2Cidr:
    Type: String

  vpcId:
    Type: String

Resources:

  LoadTestECRRepo: 
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: !Ref ecrRepo

  TaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      Family: !Ref taskName
      Cpu: 1024
      Memory: 2048
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !Ref TaskExecutionRole
      TaskRoleArn: !Ref TaskExecutionRole
      ContainerDefinitions:
        - Name: !Ref taskName
          Cpu: 1024
          Memory: 2048
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ecrRepo}:${loadTestImage}"
          PortMappings:
            - ContainerPort: 5557
              HostPort: 5557
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGroup
              awslogs-stream-prefix: !Ref AWS::StackName

  LocustSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: "Security Group for ML Load testing"
      GroupName: "ml-serving-load-testing"
      SecurityGroupEgress: 
        - CidrIp: 0.0.0.0/0
          Description: "all outbound"
          IpProtocol: -1
          FromPort: -1
          ToPort: -1
      SecurityGroupIngress: 
        - CidrIp: !Ref subnet1Cidr
          Description: vpc-private-subnets
          IpProtocol: tcp
          FromPort: 5557
          ToPort: 5557
        - CidrIp: !Ref subnet2Cidr
          Description: vpc-private-subnets
          IpProtocol: tcp
          FromPort: 5557
          ToPort: 5557
      VpcId: !Ref vpcId


  TaskExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: logs
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'
        - PolicyName: ecr
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - 'ecr:BatchCheckLayerAvailability'
                  - 'ecr:GetDownloadUrlForLayer'
                  - 'ecr:BatchGetImage'
                Resource: 
                  - !Sub "arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/${ecrRepo}"
              - Effect: Allow
                Action:
                  - 'ecr:GetAuthorizationToken'
                Resource: '*'
        - PolicyName: ecs
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - 'ecs:ListTasks'
                  - 'ecs:DescribeTasks'
                Resource: 
                  - '*'
        - PolicyName: s3
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - 's3:List*'
                  - 's3:GetBucketLocation'
                Resource:
                  - !Sub 'arn:aws:s3:::${perfTestBucket}'
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:DeleteObject
                  - s3:HeadObject
                Resource:
                  - !Sub 'arn:aws:s3:::${perfTestBucket}/*'

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /fargate/${AWS::StackName}
      RetentionInDays: 7

  